#pragma once

#include <juce_core/juce_core.h>

namespace pc::test
{

inline juce::MemoryBlock bytes (const char* s)
{
    return juce::MemoryBlock (s, std::strlen (s));
}

inline juce::MemoryBlock bytes (std::initializer_list<unsigned char> b)
{
    juce::MemoryBlock m;
    for (auto c : b)
        m.append (&c, 1);
    return m;
}

inline juce::File fixturesDir()
{
    return juce::File (PLAYLISTCONTROL_FIXTURES_DIR);
}

inline juce::MemoryBlock fixture (const juce::String& relative)
{
    juce::MemoryBlock m;
    fixturesDir().getChildFile (relative).loadFileAsData (m);
    return m;
}

// Temporary folder deleted when the test ends.
class TempDir
{
public:
    TempDir()
        : dir (juce::File::getSpecialLocation (juce::File::tempDirectory)
                   .getChildFile ("PlaylistControlTests")
                   .getNonexistentChildFile ("run", "", false))
    {
        dir.createDirectory();
    }
    ~TempDir() { dir.deleteRecursively(); }

    juce::File dir;
};

// Copy of the installation fixture (tests/fixtures/installation, generated by
// tools/make_fixtures.py) that tests can modify freely. Returns the pgm folder.
inline juce::File copyInstallationFixture (const TempDir& temp)
{
    auto root = temp.dir.getChildFile ("Playlist");
    fixturesDir().getChildFile ("installation").copyDirectoryTo (root);

    // Folders.xml holds absolute paths; the fixture uses a placeholder.
    auto folders = root.getChildFile ("pgm").getChildFile ("Folders.xml");
    juce::MemoryBlock m;
    folders.loadFileAsData (m);
    auto text = juce::String::fromUTF8 (static_cast<const char*> (m.getData()) + 3, (int) m.getSize() - 3)
                    .replace ("%PLAYLIST_ROOT%", root.getFullPathName());
    juce::MemoryOutputStream out;
    const unsigned char bom[] = { 0xEF, 0xBB, 0xBF };
    out.write (bom, sizeof (bom));
    out.write (text.toRawUTF8(), text.getNumBytesAsUTF8());
    folders.replaceWithData (out.getData(), out.getDataSize());
    return root.getChildFile ("pgm");
}

} // namespace pc::test
